CREATE TABLE movie
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title        VARCHAR(255),
    gender       VARCHAR(255),
    date_watched date,
    rating       INTEGER                                 NOT NULL,
    CONSTRAINT pk_movie PRIMARY KEY (id)
);
