
CREATE TABLE movieuser
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       VARCHAR(255),
    email      VARCHAR(255),
    avatar_url VARCHAR(255),
    CONSTRAINT pk_movieuser PRIMARY KEY (id)
);

ALTER TABLE movieuser
    ADD CONSTRAINT uc_movieuser_email UNIQUE (email);
